services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  backend:
    build:
      context: ./backend
      dockerfile: src/UrlShortener.Web/Dockerfile
    container_name: backend
    environment:
      ASPNETCORE_HTTP_PORTS: 5000
      JWTOptions__JWTSecret: ${JWTOptions__JWTSecret}
      VirusTotal__ApiKey: ${VirusTotal__ApiKey}
      Database__ConnectionString: ${Database__ConnectionString}
    ports:
      - "5000:5000"
    depends_on:
      - sqlserver

volumes:
  sql_data:
